# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sun Jun 28 18:50:42 2009

import wx
import sys

# begin wxGlade: dependencies
# end wxGlade
from SubscriptionsList import SubscriptionsList
# begin wxGlade: extracode

# end wxGlade

class SubscriptionsPane(wx.Panel):
    def __init__(self, *args, **kwds):
        if "channel" in kwds:
            self.channel = kwds.pop("channel")
        else:
            self.channel = None

        # begin wxGlade: SubscriptionsPane.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.sizer_10_staticbox = wx.StaticBox(self, -1, "Subscribed Programmes")
        self.sizer_9_staticbox = wx.StaticBox(self, -1, "Hidden Programmes")
        self.hidden_list = SubscriptionsList(self, -1, style=wx.LC_REPORT|wx.LC_VIRTUAL|wx.LC_NO_HEADER|wx.SUNKEN_BORDER)
        self.show_button = wx.Button(self, -1, "Show -->")
        self.hide_button = wx.Button(self, -1, "<-- Hide")
        self.subscribed_list = SubscriptionsList(self, -1, style=wx.LC_REPORT|wx.LC_VIRTUAL|wx.LC_NO_HEADER|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        if self.channel is not None:
            self.update()

    def __set_properties(self):
        # begin wxGlade: SubscriptionsPane.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SubscriptionsPane.__do_layout
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.StaticBoxSizer(self.sizer_10_staticbox, wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.StaticBoxSizer(self.sizer_9_staticbox, wx.HORIZONTAL)
        sizer_9.Add(self.hidden_list, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_9, 1, wx.LEFT|wx.TOP|wx.BOTTOM|wx.EXPAND, 5)
        sizer_8.Add((0, 0), 1, 0, 0)
        sizer_8.Add(self.show_button, 0, wx.ALL, 5)
        sizer_8.Add(self.hide_button, 0, wx.ALL, 5)
        sizer_8.Add((0, 0), 1, 0, 0)
        sizer_7.Add(sizer_8, 0, wx.EXPAND, 0)
        sizer_10.Add(self.subscribed_list, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_10, 1, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.EXPAND, 5)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        # end wxGlade

# Always show programmes marked "unsubscribed" in the hidden list.
#    Show in grey if no longer available.
# Always show programmes marked "subscribed" in the subscribed list.
#    Show in grey if no longer available.
#
# For all other programmes, if "require_subscription" settings is true:
#    Show as unsubscribed
# else:
#    Show as subscribed


    def update(self): 
        unsubscribed_programmes = set(self.channel.channel_settings.
                                      unsubscribed_programmes)
        subscribed_programmes = set(self.channel.channel_settings.
                                    subscribed_programmes)

        if self.channel.channel_settings.require_subscription:
            unsubscribed_programmes = unsubscribed_programmes.union(
                self.channel.unsubscribed_programmes.keys())
        else:
            subscribed_programmes = subscribed_programmes.union(
                self.channel.subscribed_programmes.keys())

        available_unsubscribed = (set(self.channel.all_programmes) -
                                  subscribed_programmes)
        available_subscribed = (set(self.channel.all_programmes) -
                                unsubscribed_programmes)

        self.hidden_list.update(list(unsubscribed_programmes), 
                                emphasis=available_unsubscribed)
        self.subscribed_list.update(list(subscribed_programmes),
                                    emphasis=available_subscribed)

# end of class SubscriptionsPane


