# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Tue Jun 16 21:33:12 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class DownloadLog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: DownloadLog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.log_text = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.TE_WORDWRAP)
        self.button_1 = wx.Button(self, wx.ID_CLOSE, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: DownloadLog.__set_properties
        self.SetTitle("Download Log")
        self.button_1.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DownloadLog.__do_layout
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_5.Add(self.log_text, 1, wx.EXPAND, 0)
        sizer_5.Add(self.button_1, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        self.SetSizer(sizer_5)
        sizer_5.Fit(self)
        self.Layout()
        # end wxGlade

# end of class DownloadLog


