# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Wed May 13 20:53:38 2009

import wx

from EpisodeToolbar import EpisodeToolbar

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class EpisodePanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: EpisodePanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.episode_toolbar = EpisodeToolbar(self, -1)
        self.episode_list = wx.SimpleHtmlListBox(self, -1, choices=[])

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

        self.episodes = []

    def __set_properties(self):
        # begin wxGlade: EpisodePanel.__set_properties
        self.episode_list.SetWindowStyle(wx.STATIC_BORDER)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: EpisodePanel.__do_layout
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_4.Add(self.episode_toolbar, 0, wx.EXPAND, 2)
        sizer_4.Add(self.episode_list, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND, 2)
        self.SetSizer(sizer_4)
        sizer_4.Fit(self)
        # end wxGlade

    def update(self, programme):
        """ Update the episode list with the selected programme """
        self.episode_list.Clear()
        if programme is None:
            return

        for episode in programme.episodes:
            self.episode_list.Append(self._generate_html(episode),
                                     clientData=episode)

        # Select the first episode
        self.episode_list.SetSelection(0)
        self.update_episode_toolbar(self.episode_list.GetClientData(0))

    def _generate_html(self, episode):
         if episode.downloaded:
             html = ("<font color=grey>%s</font><br>" % episode.episode +
                     "<table><td>&nbsp;</td><td>" + # Indent
                     "<font color=grey size=-1>%s</font>" % episode.desc +
                     "</td></table>")
         elif episode.ignored:
             html = ("<em><font color=red>%s</font><br>" % episode.episode +
                     "<table><td>&nbsp;</td><td>" + # Indent
                     "<font color=red size=-1>%s</font>" % episode.desc +
                     "</td></table></em>")
         else:
            html = ("<strong>%s</strong><br>" % episode.episode +
                    "<table><td>&nbsp;</td><td>" + # Indent
                    "<font size=-1>%s</font>" % episode.desc +
                    "</td></table>")

         return html

    def get_selected_episode(self):
        """ Returns the episode object for the current selection """
        index = self.episode_list.GetSelection()
        if index == wx.NOT_FOUND:
            return None
        else:
            return self.episode_list.GetClientData(index)

    def refresh_selected_episode(self):
        index = self.episode_list.GetSelection()
        if index == wx.NOT_FOUND:
            return

        episode = self.episode_list.GetClientData(index)
        self.episode_list.SetString(index, self._generate_html(episode))
        self.update_episode_toolbar(episode)

    def update_episode_toolbar(self, episode):
        self.episode_toolbar.update(episode)

    def select_next_episode(self):
        """ 
        Selects the next episode not marked as "ignored" or "downloaded"
        """        
        index = self.episode_list.GetSelection()
        if index == wx.NOT_FOUND:
            self.update_episode_toolbar(None)
            return
        start_index = index

        while index < self.episode_list.GetCount():
            episode = self.episode_list.GetClientData(index)
            if not episode.downloaded and not episode.ignored:
                self.episode_list.SetSelection(index)
                self.update_episode_toolbar(self.episode_list.GetClientData(index))
                return
            index += 1

        return 

# end of class EpisodePanel


