#----------------------------------------------------------------------
# This file was generated by /usr/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

IPlayer = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABHNCSVQICAgIfAhkiAAACNNJ"
    "REFUaIG9mnuMVFcdxz/n3DszOzu77EApBYHysFEsVtfSf7SZsqu1NTFBiGnH+KC7ppLoH61B"
    "sVatUOsDaxTrP6ZasxtNakajSFuJKGW3nRhfNNkSpNTgCgiBrBQGdmcfM+ee4x/3zjCPc2fu"
    "gvGbHLLMef2+5/xe55wrjDFcL/Ju1gXuAaaAHcBS4FagM2hSAo4AF4ATwAHgYEblZq93bnGt"
    "BPJuNg18ALgPX/iueQ4xDRwEfgXsz6jchWuRY94E8m62A3gIeBRIX8ukFkwBHwQOZ1Ruej4d"
    "50Ug72Y/CTwOrJiXeNExAewEnsmonIrSIRKBvJtdDfwSuON6pJsHjgFbMir3j3YN2xLIu9l7"
    "gBxt1KUDhx4Tp8fEiSFJGgeJAMBgmBYeCs1lUeKyKDGD1062aWAwo3K/uGYCeTe7FfgJ4Ia1"
    "udF0sMR0kDShTayYxWNCzjAh2jqihzMq94OwylACeTd7P/7KW3GDSbBCp3CRUeQNhcJwVha5"
    "0JrIpzIq94ytwkog72ZvB/Jc9eNVJI3DStNFyrh4GMp4eDSPIQCJIIaDE6hSK8wIxWlRZFpY"
    "bbcE3JtRudG2BPJu9k3AX7B4mpRxWaO7cRB4GGaJ5ChI4ETeqTOyyBtizlY1Abw7o3LjoQTy"
    "blbir/x7GnsvMgmW66sbMouHxtC9axPdOzc1zaYL0xSfOsjkrucAiCGJRSRxTs6EqdQRYEOt"
    "i20ccbtN+KRxWKqTeJhAbTQKjdO70io8gEx30r1zEz1Dg2gMc3jMoKpjtCpLdAdJ49iGfQfw"
    "RN08lT/ybnYJfhCpQwzJMt2JxlRLZSLSSavwtUgN3MnikR2YdJISmhlU3VhhZYVOEbfv2PYg"
    "LtUTANZhyWeW6iQuInSiKOjoW8dNI1+AdJIymulgJ1oREMHcFsSBL9cRyLvZBcBvG1v2mDgJ"
    "I60TeBEInO3fzdzYaX/W3ptZOvIIbu/KyCTiRpI2cdvQWwONqe7AAA2rL4CFOh6qpxqNaUOg"
    "OHqMf/d/s0oi0Xszy0e+SKx3BQqPacqU0S3tYaGO29xwHF9jqhH2Y40tukwMEyKiqRhzocj0"
    "6GuhBDwMXqHIqf5vsGxoG92bNyDTnawY+RJntnyf6dHXKKNJ4lbTDhtSxuWKKDf+/DTwNvGy"
    "c38a+A8N6cIyL9kyAFWMsR1cJAoNwPKhbSwcuKtad3bwR1wafhloHSsMcNaxZtlrnEG5fhOQ"
    "rf01biQp42KCzrYiEahg+1sZYhzfHZbRXN53GAR09d0KwILNG5g9NUFx7CRlNAKBRDTNBVAW"
    "BiWaFuzvzqBcvxW4s/bXDhxiRrYkUKSMClQsrHgYFJoELiAoo5kcPUbp1AXSm/3MvGfzHcRW"
    "L+bSvsOU0ehgcWzjzQndSOCiix8c6uAa0VI9FJoymgV951k3Mhra7q/iI3gYOjA4CBI4TKOY"
    "GB5FY1i1ZytOOsUNAxsxwPjgD5lBoQK7qEVIDH+LBG5p+tkYPHTL4qtPf6jwFaKqpo/A310P"
    "zfnhEY72P44qFAFYPLCRt448BukkM6ggal/tG7Ket0j8G4R6+SFSyLdlobUIa19Z3Stj/+JI"
    "/64qiZ6+9aza80A1UaztF+KyF0ks0de0CTB+INOBxrYioIN2zdG7I/BxV8bG+fOaT1dJ3DTQ"
    "h4dmLkgW20R913qMirKyCtP2UKiCcWzjVZJCD0Ny9Y1X+xSKqMCDtZMDfN8/RcMutOuoAu/i"
    "tdmBiv9vHM/DcIU5DLCo7+28a++juOkUACefeh6FJoaMQkC5wHkaDNkLViAMUXOhigC17ebw"
    "KFLGACsG3sc7hx6q1p0ZfpHXd/0cgBROlEB50cW/6qsnIAzNMaNesIputyZQvwNzeExRAmDl"
    "wGSd8ON9+zj6kn/s7SKODE59VYjqP7U4USFQB10XA+2CqQhe6KoN+NnndHAE3TD0WVYN3F1t"
    "98pgH6de6gqEj+EiLOopEBYCEvhj08wiPP+v9ULtjd23kwJzTFLCQ3P70MN1wv9tcA/jw51o"
    "NClc4tjTd4RVqV9xgUPN8ouWwqmqF4q2AwpFPJ0is/erLOnzA3+pUCS/5WtMjB7xU3cSuC0M"
    "17ETOCQzKjeBf1iu7yDtK+GXin+PFgecdCfvHfl2jfBT/KF/B+dGxxBAT6DzYfNJaU0kTmdU"
    "7mil5meNtVI4baNwa/F94+3pXcvdI0+ysPfNAFwc+ycH+ndwYewEEkE3cURgsGFFCiuBZ+Fq"
    "jvRT/LvIKgQQk07oqgxFcKNrB97PvSPfYVGN8Pv7P89364Snpa3FpGM77Cjgx1UCgRoNN7aK"
    "CxeEfXU+HoFAZmgH8bTvXc6NvsoL/Z9jtjDJg0jSJIDWORdC+DI04zeVC67avfkWBE66Bp0y"
    "BpZVihLIKnh9+ADP9W9npjBJDEk38bZezmDoFDHbcAp4rPKfKoGMyp2prajAQdIlE3WDCwQa"
    "zeWT59oKf3z4dxwa3I1G04nDggjCawxdMoFj1/3vZVTueBOBSiUWj+QKSaeM1xDwiRVOnuPF"
    "wd3MFaaaZrkwdoL9W77CwcHdeBi6iNNJLJLwnTJGTFhv5k7gvxBVYbvcXQv8CVjS2LtkPC7p"
    "GTR+MvcGs22VyDfWWNMJK6ztAtlB0q73BSCTUbmjLQkEJPrwn0KbbpXKRlMwM5SMf60+SYkS"
    "ml83ULkPSRxJiljLK5MKYkKyUCTDVl7hPzm90FjR6oHjQQJXZcOkmaOgr/uZF4C07KBLJFrR"
    "fCSjck/aKto9MX0GeIqQJyYPTdGUKehZ2t3SNU0MdIkEC2Si3dtBqPAQ7ZHvLmAvsKhVu6Ip"
    "M2PKlPBQpjnVlghcIYnjkBQuKWG986zFFPDhjMr9vlWjqM+sa4Hn8T8f+H9gHPhQo8HaEOnJ"
    "JIh6G4CvYwl2/0MoYCNwWxTh4do+NViLH/A+isVLXQeeBZ6oDVJRcD0feywBtgEPYLsci4bT"
    "wCeA8SATmDeumUAt8m52Hf4XK7cBvfiEGl/2p4DjwFHgVeBQRuWaov588V8qt2LHWNS7ywAA"
    "AABJRU5ErkJggg==")
getIPlayerData = IPlayer.GetData
getIPlayerImage = IPlayer.GetImage
getIPlayerBitmap = IPlayer.GetBitmap

