# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Wed May 13 21:21:56 2009

import wx

# begin wxGlade: dependencies
from EpisodePanel import EpisodePanel
from ChannelPanel import ChannelPanel
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class MeTvFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        self.app = wx.App(0)
        kwds['parent'] = None

        # begin wxGlade: MeTvFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.channel_panel = ChannelPanel(self, -1)
        self.static_line_1 = wx.StaticLine(self, -1, style=wx.LI_VERTICAL)
        self.episode_panel = EpisodePanel(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MeTvFrame.__set_properties
        self.SetTitle("meTV")
        self.SetSize((600, 500))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MeTvFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.channel_panel, 3, wx.EXPAND, 0)
        sizer_1.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_1.Add(self.episode_panel, 4, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def start(self):
        self.Show()
        self.app.MainLoop()

    def delete_all_channels(self):
        self.channel_panel.clear()

    def add_channel(self, channel):
        self.channel_panel.add(channel)
            
    def update_channel(self, channel):
        self.channel_panel.update(channel)

    def get_selected_programme(self):
        return self.channel_panel.get_selected_programme()

    def delete_programme(self, programme):
        self.channel_panel.delete_programme(programme)

    def update_episodes(self, programme):
        self.episode_panel.update(programme)

    def get_selected_episode(self):
        return self.episode_panel.get_selected_episode()

# end of class MeTvFrame


