# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Tue Jun 16 21:34:19 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class DownloadLogDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        self.episode = kwds.pop("episode")
        self._chunk_count = 0

        # begin wxGlade: DownloadLogDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE|wx.RESIZE_BORDER|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.log_text = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY|wx.HSCROLL)
        self.button_1 = wx.Button(self, wx.ID_CLOSE, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self._on_close, self.button_1)
        # end wxGlade
        
    def __set_properties(self):
        # begin wxGlade: DownloadLogDialog.__set_properties
        self.SetTitle("Download Log")
        self.SetSize((600, 400))
        self.button_1.SetDefault()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: DownloadLogDialog.__do_layout
        sizer_5 = wx.BoxSizer(wx.VERTICAL)
        sizer_5.Add(self.log_text, 1, wx.ALL|wx.EXPAND, 5)
        sizer_5.Add(self.button_1, 0, wx.ALL|wx.ALIGN_RIGHT, 5)
        self.SetSizer(sizer_5)
        self.Layout()
        # end wxGlade

    def ShowModal(self, *args, **kwds):
        self.update()
        wx.Dialog.ShowModal(self, *args, **kwds)

    def _on_close(self, event): # wxGlade: DownloadLogDialog.<event_handler>
        self.Close()

    def update(self):
        """ Append any new chunks to the end of the log """
        new_chunk_count = len(self.episode.download_chunks)
        for chunk in self.episode.download_chunks[self._chunk_count:]:
            self.log_text.WriteText(chunk)
        self._chunk_count = new_chunk_count
# end of class DownloadLogDialog


