# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Wed May 13 21:01:20 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class EpisodeToolbar(wx.ToolBar):
    ID_DOWNLOAD = 101
    ID_IGNORE = 102

    def __init__(self, *args, **kwds):
        # begin wxGlade: EpisodeToolbar.__init__
        kwds["style"] = wx.TB_FLAT|wx.TB_TEXT
        wx.ToolBar.__init__(self, *args, **kwds)
        self.AddLabelTool(self.ID_DOWNLOAD, "Download", wx.Bitmap("C:\\linuxshare\\projects\\iplayer-get\\metv\\view\\iplayer-temp.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Download the selected episode", "")
        self.AddLabelTool(self.ID_IGNORE, "Ignore", wx.Bitmap("C:\\linuxshare\\projects\\iplayer-get\\metv\\view\\iplayer-temp.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "Mark the selected episode as \"Ignored\"", "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: EpisodeToolbar.__set_properties
        self.SetToolBitmapSize((48, 48))
        self.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: EpisodeToolbar.__do_layout
        pass
        # end wxGlade

# end of class EpisodeToolbar


