# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sun Jun 28 18:50:42 2009

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class SubscriptionsPane(wx.Panel):
    def __init__(self, *args, **kwds):
        if "channel" in kwds:
            self.channel = kwds.pop("channel")

        # begin wxGlade: SubscriptionsPane.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.sizer_10_staticbox = wx.StaticBox(self, -1, "Subscribed Programmes")
        self.sizer_9_staticbox = wx.StaticBox(self, -1, "Hidden Programmes")
        self.hidden_list = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.LC_NO_HEADER|wx.SUNKEN_BORDER)
        self.show_button = wx.Button(self, -1, "Show -->")
        self.hide_button = wx.Button(self, -1, "<-- Hide")
        self.subscribed_list = wx.ListCtrl(self, -1, style=wx.LC_REPORT|wx.LC_NO_HEADER|wx.SUNKEN_BORDER)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: SubscriptionsPane.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SubscriptionsPane.__do_layout
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_10 = wx.StaticBoxSizer(self.sizer_10_staticbox, wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_9 = wx.StaticBoxSizer(self.sizer_9_staticbox, wx.HORIZONTAL)
        sizer_9.Add(self.hidden_list, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_9, 1, wx.LEFT|wx.TOP|wx.BOTTOM|wx.EXPAND, 5)
        sizer_8.Add((0, 0), 1, 0, 0)
        sizer_8.Add(self.show_button, 0, wx.ALL, 5)
        sizer_8.Add(self.hide_button, 0, wx.ALL, 5)
        sizer_8.Add((0, 0), 1, 0, 0)
        sizer_7.Add(sizer_8, 0, wx.EXPAND, 0)
        sizer_10.Add(self.subscribed_list, 1, wx.EXPAND, 0)
        sizer_7.Add(sizer_10, 1, wx.RIGHT|wx.TOP|wx.BOTTOM|wx.EXPAND, 5)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        # end wxGlade

# end of class SubscriptionsPane


